import PDFDocument from 'pdfkit';
import { calculate, euro } from '../src/benefits.js';

const C={blue:'#2563EB',green:'#16A34A',dark:'#172033',muted:'#667085',light:'#F6F8FB',border:'#DDE3EC',yellow:'#FFF7E6',amber:'#D97706',paleGreen:'#ECFDF3',paleBlue:'#EFF6FF'};
const fullName=o=>[o.customer_name,o.customer_surname].filter(Boolean).join(' ')||'Cliente BonusFatto';
const dateIt=d=>new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Rome'}).format(d);
const clean=(v,max=600)=>String(v??'').trim().slice(0,max);
function title(doc,t){doc.font('Helvetica-Bold').fontSize(19).fillColor(C.dark).text(t);doc.moveDown(.45)}
function h2(doc,t){doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(t);doc.moveDown(.25)}
function body(doc,t,opt={}){doc.font('Helvetica').fontSize(9.3).fillColor(C.dark).text(t,{lineGap:3,...opt});doc.moveDown(.45)}
function small(doc,t){doc.font('Helvetica').fontSize(7.8).fillColor(C.muted).text(t,{lineGap:2})}
function box(doc,text,bg=C.light,stroke=C.border){const x=48,w=499,p=10,h=doc.heightOfString(text,{width:w-p*2,lineGap:3})+p*2;if(doc.y+h>760)doc.addPage();const y=doc.y;doc.roundedRect(x,y,w,h,5).fillAndStroke(bg,stroke);doc.fillColor(C.dark).font('Helvetica').fontSize(9).text(text,x+p,y+p,{width:w-p*2,lineGap:3});doc.y=y+h+10}
function kv(doc,rows,bg=C.light,stroke=C.border){const x=48,w=499,left=165,p=7;let y=doc.y;for(const[k,v]of rows){const h=Math.max(doc.heightOfString(String(k),{width:left-p*2}),doc.heightOfString(String(v),{width:w-left-p*2}))+p*2;if(y+h>760){doc.addPage();y=doc.y}doc.rect(x,y,w,h).fillAndStroke(bg,stroke);doc.moveTo(x+left,y).lineTo(x+left,y+h).strokeColor(stroke).stroke();doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(8).text(String(k),x+p,y+p,{width:left-p*2});doc.fillColor(C.dark).font('Helvetica').fontSize(8.5).text(String(v),x+left+p,y+p,{width:w-left-p*2,lineGap:2});y+=h}doc.y=y+10}
function badge(doc,text,kind='green'){const map={green:[C.paleGreen,C.green],blue:[C.paleBlue,C.blue],yellow:[C.yellow,C.amber]};const[bg,fg]=map[kind];const w=Math.min(499,doc.widthOfString(text)+18),y=doc.y;doc.roundedRect(48,y,w,20,4).fillAndStroke(bg,fg);doc.fillColor(fg).font('Helvetica-Bold').fontSize(7.5).text(text,57,y+6,{width:w-18});doc.y=y+27}
function pageHeaderFooter(doc,order){const pages=doc.bufferedPageRange();for(let i=pages.start;i<pages.start+pages.count;i++){doc.switchToPage(i);const old=doc.y;doc.font('Helvetica-Bold').fontSize(9).fillColor(C.blue).text('Bonus',48,25,{continued:true,lineBreak:false}).fillColor(C.green).text('Fatto.it',{lineBreak:false});doc.font('Helvetica').fontSize(7).fillColor(C.muted).text(`Relazione ${order.order_code}`,330,27,{width:217,align:'right',lineBreak:false});doc.moveTo(48,42).lineTo(547,42).strokeColor(C.border).lineWidth(.5).stroke();doc.moveTo(48,776).lineTo(547,776).strokeColor(C.border).lineWidth(.5).stroke();doc.font('Helvetica').fontSize(7).fillColor(C.muted).text('Documento informativo personalizzato - BonusFatto.it',48,784,{lineBreak:false});doc.text(`Pagina ${i+1}`,480,784,{width:67,align:'right',lineBreak:false});doc.y=old}}
function displayAmount(b){if(typeof b.amount==='string')return euro(b.amount);if(Number.isFinite(b.amount))return `${euro(b.amount)}${b.period?` · ${b.period}`:''}`;return 'Importo non determinabile con i dati disponibili'}
function levelFor(b){if(b.eligibility==='spetta-profilo'||b.eligibility==='stimabile')return['PROFILO COMPATIBILE','green'];if(b.eligibility==='potenzialmente-assegnabile'||b.eligibility==='graduatoria')return['POTENZIALMENTE ASSEGNABILE','yellow'];if(b.eligibility==='compatibile')return['COMPATIBILE - CONDIZIONE DA CONFERMARE','yellow'];return['DA APPROFONDIRE','yellow']}
function metadataProfile(metadata={}){const p={};for(const[k,v]of Object.entries(metadata)){if(!k.startsWith('p_'))continue;p[k.slice(2)]=v}if(p.childAges)p.childAges=String(p.childAges).split(',').filter(Boolean).map(Number).filter(Number.isFinite);for(const key of ['children','household','annualRent','adiFamilyIncome','adiMovableAssets','adiRealEstateAssets','renovationAmount'])if(p[key]!==undefined&&p[key]!=='')p[key]=Number(p[key]);return p}
async function profileFromStripe(order){const secret=clean(process.env.STRIPE_SECRET_KEY,1200),id=clean(order.stripe_session_id,255);if(!secret||!/^cs_(test|live)_[A-Za-z0-9]+$/.test(id))return{};try{const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${secret}`}});const s=await r.json();if(!r.ok)return{};return metadataProfile(s.metadata||{})}catch{return{}}}
export function customerEmailText(order){return `Oggetto: Richiesta informazioni agevolazioni TARI 2026 - ISEE ${euro(order.isee)} - Comune ${order.calculation_municipality}\n\nGentile Ufficio Tributi del Comune di ${order.calculation_municipality},\n\nsono residente nel Comune e dispongo di un ISEE 2026 pari a ${euro(order.isee)}.\n\nChiedo cortesemente di conoscere le eventuali agevolazioni, riduzioni o esenzioni TARI comunali ulteriori rispetto al bonus sociale rifiuti nazionale, con indicazione di requisiti, percentuali applicabili, documentazione necessaria, modalità di presentazione e scadenze.\n\nQualora sia prevista una procedura a domanda, chiedo anche il relativo modulo o il collegamento al servizio online.\n\nResto a disposizione per trasmettere la documentazione attraverso i canali ufficiali dell'Ente.\n\nCordiali saluti,\n${fullName(order)}\n${order.fiscal_code||'[Codice fiscale]'}\n[Codice utenza TARI]\n${order.customer_email||'[Recapito]'}`}

export async function createBonusFattoReport(order){
 const profile=await profileFromStripe(order);const input={isee:Number(order.isee),children:Number(order.children),municipality:{name:order.calculation_municipality},profile};const result=calculate(input);const doc=new PDFDocument({size:'A4',margins:{top:58,bottom:48,left:48,right:48},bufferPages:true,info:{Title:`BonusFatto - ${order.order_code}`,Author:'BonusFatto.it'}});const chunks=[];doc.on('data',c=>chunks.push(c));const done=new Promise((resolve,reject)=>{doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});
 doc.moveDown(2);doc.font('Helvetica-Bold').fontSize(29).fillColor(C.blue).text('Bonus',{continued:true}).fillColor(C.green).text('Fatto.it');doc.moveDown(.35);doc.font('Helvetica-Bold').fontSize(20).fillColor(C.dark).text('Relazione personalizzata bonus e agevolazioni 2026');doc.moveDown(.5);body(doc,`Relazione elaborata per ${fullName(order)} sulla base dei dati forniti nel questionario e al momento dell'acquisto.`);kv(doc,[['Codice relazione',order.order_code],['Data elaborazione',dateIt(new Date())],['Cliente',fullName(order)],['Comune analizzato',order.calculation_municipality],['ISEE',euro(order.isee)],['Figli a carico',String(order.children??0)]],C.paleBlue,C.blue);box(doc,`ESITO SINTETICO\n${result.benefits.length} agevolazioni individuate. Le prestazioni determinabili riportano importo o spettanza; le misure a graduatoria sono indicate come potenzialmente assegnabili.`,C.paleGreen,C.green);body(doc,'Il motore utilizza le risposte del questionario avanzato. “Profilo compatibile” significa che i requisiti verificabili con i dati forniti risultano soddisfatti; l’ente competente mantiene la verifica amministrativa finale.');
 doc.addPage();title(doc,'1. TARI: bonus nazionale e riduzione comunale');if(result.tariNationalEligible){badge(doc,'PROFILO COMPATIBILE - BONUS TARI NAZIONALE','green');kv(doc,[['Riduzione','25% della TARI dovuta'],['Stima in euro',euro(result.tariEstimatedSaving)],['Base convenzionale usata',euro(result.tariBase)]],C.paleGreen,C.green)}if(result.tariLocalPercent>0){badge(doc,'PROFILO COMPATIBILE - RIDUZIONE COMUNALE','green');kv(doc,[['Comune',order.calculation_municipality],['Riduzione fascia',`${result.tariLocalPercent}%`],['Stima in euro',euro(result.tariBase*result.tariLocalPercent/100)],['Scadenza',result.tariLocalRule?.deadlineLabel||'Da verificare sulla fonte ufficiale'],['Fonte',result.tariLocalRule?.sourceUrl||'Fonte comunale']],C.paleBlue,C.blue)}box(doc,'Le percentuali nazionale e comunale non vengono sommate automaticamente: l’applicazione concreta dipende dalla posizione TARI e dalle regole comunali vigenti.',C.yellow,C.amber);
 doc.addPage();title(doc,'2. Bonus e agevolazioni individuate');body(doc,'Per ogni misura sono mostrati l’esito del profilo, l’importo quando determinabile e la motivazione sintetica.');for(const b of result.benefits){if(b.id==='tari'||b.id.startsWith('tari-local-'))continue;if(doc.y>680)doc.addPage();const[lev,kind]=levelFor(b);badge(doc,lev,kind);h2(doc,b.name);kv(doc,[['Esito economico',displayAmount(b)],['Nota',b.description],['Fonte',b.sourceUrl||'Fonte istituzionale della misura']],kind==='green'?C.paleGreen:C.yellow,kind==='green'?C.green:C.amber)}
 doc.addPage();title(doc,'3. Dati principali utilizzati');kv(doc,[['Nucleo',`${profile.household??'-'} componenti`],['Età figli',Array.isArray(profile.childAges)?profile.childAges.join(', '):'-'],['Disabilità nel nucleo',profile.disability??'-'],['Persona 60+',profile.over60??'-'],['Persona 65+',profile.over65??'-'],['Abitazione',profile.housing??'-'],['Utenza luce idonea',profile.electricitySupply??'-'],['Utenza gas idonea',profile.gasSupply??'-'],['Utenza acqua idonea',profile.waterSupply??'-'],['Reddito familiare ADI',profile.adiFamilyIncome!=null?euro(profile.adiFamilyIncome):'-'],['Patrimonio mobiliare ADI',profile.adiMovableAssets!=null?euro(profile.adiMovableAssets):'-'],['Patrimonio immobiliare ADI',profile.adiRealEstateAssets!=null?euro(profile.adiRealEstateAssets):'-'],['Spese ristrutturazione',profile.renovationAmount!=null?euro(profile.renovationAmount):'-']],C.light,C.border);body(doc,'Questa sezione rende trasparente quali risposte sono state effettivamente utilizzate dal motore.');
 doc.addPage();title(doc,'4. Cosa fare adesso');body(doc,'1. Conserva l’attestazione ISEE/DSU 2026 valida.');body(doc,`2. Per la TARI verifica la posizione effettiva presso il Comune di ${order.calculation_municipality}, soprattutto quando la riduzione locale è soggetta a domanda.`);body(doc,'3. Per i bonus automatici o INPS, conserva la documentazione e controlla l’effettiva lavorazione dell’ente.');body(doc,'4. Per le detrazioni fiscali, conserva fatture, bonifici e documentazione dell’intervento.');h2(doc,'Checklist documenti utile');['Attestazione ISEE/DSU 2026','Documento di identità e codice fiscale','Ultimo avviso o bolletta TARI e codice utenza','Bolletta o dati delle forniture domestiche quando rilevanti','Documentazione delle spese e dei requisiti dichiarati'].forEach(x=>body(doc,`• ${x}`));
 doc.addPage();title(doc,'5. Email / PEC pronta per l’Ufficio Tributi');body(doc,'La comunicazione è riportata su una pagina autonoma per poter essere copiata, stampata o utilizzata senza interruzioni tra una pagina e l’altra.');box(doc,customerEmailText(order),C.light,C.border);
 doc.addPage();title(doc,'6. Fonti e avvertenze');if(result.tariLocalRule?.sourceUrl)body(doc,`Fonte TARI comunale: ${result.tariLocalRule.sourceUrl}`);body(doc,`Data di elaborazione: ${dateIt(new Date())}.`);body(doc,'Metodo: la relazione applica le regole presenti nel motore BonusFatto ai dati forniti dall’utente. Le misure con assegnazione a graduatoria vengono indicate come potenzialmente assegnabili anche quando il profilo soddisfa i requisiti verificabili.');box(doc,'NOTA LEGALE\nLa relazione ha finalità informativa e orientativa. Non costituisce provvedimento dell’ente né certificazione fiscale o previdenziale. L’ente competente mantiene la verifica amministrativa finale e può richiedere documentazione ulteriore.',C.yellow,C.amber);small(doc,`Relazione generata per ${fullName(order)} · ${order.order_code}`);pageHeaderFooter(doc,order);doc.end();return done;
}
