import PDFDocument from 'pdfkit';
import { calculate, euro } from '../src/benefits.js';

const C={blue:'#2563EB',green:'#16A34A',dark:'#172033',muted:'#667085',light:'#F6F8FB',border:'#DDE3EC',yellow:'#FFF7E6',amber:'#D97706',red:'#BE123C',paleRed:'#FFF1F2',paleGreen:'#ECFDF3',paleBlue:'#EFF6FF'};
const money=n=>euro(Number(n||0));
const fullName=o=>[o.customer_name,o.customer_surname].filter(Boolean).join(' ')||'Cliente BonusFatto';
const dateIt=d=>new Intl.DateTimeFormat('it-IT',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/Rome'}).format(d);
function title(doc,t){doc.font('Helvetica-Bold').fontSize(19).fillColor(C.dark).text(t);doc.moveDown(.45)}
function h2(doc,t){doc.font('Helvetica-Bold').fontSize(13).fillColor(C.dark).text(t);doc.moveDown(.25)}
function body(doc,t,opt={}){doc.font('Helvetica').fontSize(9.3).fillColor(C.dark).text(t,{lineGap:3,...opt});doc.moveDown(.45)}
function small(doc,t){doc.font('Helvetica').fontSize(7.8).fillColor(C.muted).text(t,{lineGap:2})}
function box(doc,text,bg=C.light,stroke=C.border){const x=48,w=499,p=10,h=doc.heightOfString(text,{width:w-p*2,lineGap:3})+p*2;if(doc.y+h>760)doc.addPage();const y=doc.y;doc.roundedRect(x,y,w,h,5).fillAndStroke(bg,stroke);doc.fillColor(C.dark).font('Helvetica').fontSize(9).text(text,x+p,y+p,{width:w-p*2,lineGap:3});doc.y=y+h+10}
function kv(doc,rows,bg=C.light,stroke=C.border){const x=48,w=499,left=165,p=7;let y=doc.y;for(const[k,v]of rows){const h=Math.max(doc.heightOfString(String(k),{width:left-p*2}),doc.heightOfString(String(v),{width:w-left-p*2}))+p*2;if(y+h>760){doc.addPage();y=doc.y}doc.rect(x,y,w,h).fillAndStroke(bg,stroke);doc.moveTo(x+left,y).lineTo(x+left,y+h).strokeColor(stroke).stroke();doc.fillColor(C.muted).font('Helvetica-Bold').fontSize(8).text(String(k),x+p,y+p,{width:left-p*2});doc.fillColor(C.dark).font('Helvetica').fontSize(8.5).text(String(v),x+left+p,y+p,{width:w-left-p*2,lineGap:2});y+=h}doc.y=y+10}
function badge(doc,text,kind='green'){const map={green:[C.paleGreen,C.green],blue:[C.paleBlue,C.blue],yellow:[C.yellow,C.amber],red:[C.paleRed,C.red]};const[bg,fg]=map[kind],w=doc.widthOfString(text)+18,y=doc.y;doc.roundedRect(48,y,w,20,4).fillAndStroke(bg,fg);doc.fillColor(fg).font('Helvetica-Bold').fontSize(7.5).text(text,57,y+6);doc.y=y+27}
function pageHeaderFooter(doc,order){const pages=doc.bufferedPageRange();for(let i=pages.start;i<pages.start+pages.count;i++){doc.switchToPage(i);const old=doc.y;doc.font('Helvetica-Bold').fontSize(9).fillColor(C.blue).text('Bonus',48,25,{continued:true,lineBreak:false}).fillColor(C.green).text('Fatto.it',{lineBreak:false});doc.font('Helvetica').fontSize(7).fillColor(C.muted).text(`Relazione ${order.order_code}`,330,27,{width:217,align:'right',lineBreak:false});doc.moveTo(48,42).lineTo(547,42).strokeColor(C.border).lineWidth(.5).stroke();doc.moveTo(48,776).lineTo(547,776).strokeColor(C.border).lineWidth(.5).stroke();doc.font('Helvetica').fontSize(7).fillColor(C.muted).text('Documento informativo personalizzato - BonusFatto.it',48,784,{lineBreak:false});doc.text(`Pagina ${i+1}`,480,784,{width:67,align:'right',lineBreak:false});doc.y=old}}
function missingFor(id){return({utilities:'Caratteristiche delle forniture e applicazione effettiva delle agevolazioni.',children:'Età dei figli, eventuali condizioni di disabilità, maggiorazioni e situazione familiare.',psychologist:'Domanda, disponibilità delle risorse e posizione utile nella procedura prevista.',mothers:'Situazione lavorativa, requisiti reddituali specifici ed età dei figli.',dedicated:'Composizione completa del nucleo, incompatibilità e assegnazione effettiva.',purchases:'Requisiti anagrafici, reddituali e patrimoniali.',nursery:'Età del minore, frequenza del nido e spese documentate.',newborn:'Nascita o adozione ammissibile e ulteriori requisiti della misura.',renovation:'Tipologia di spesa, immobile, pagamento tracciabile, titolarità e capienza fiscale.'})[id]||'Verifica dei requisiti specifici previsti dalla fonte ufficiale vigente.'}
function levelFor(id){if(['tari','utilities'].includes(id)||id.startsWith('tari-local-'))return['COMPATIBILITÀ ALTA','green'];if(id==='renovation')return['DATI INSUFFICIENTI','red'];return['DA APPROFONDIRE','yellow']}
function customerEmailText(order){return `Oggetto: Richiesta informazioni agevolazioni TARI 2026 - ISEE ${money(order.isee)} - Comune ${order.calculation_municipality}\n\nGentile Ufficio Tributi del Comune di ${order.calculation_municipality},\n\nsono residente nel Comune e dispongo di un ISEE 2026 pari a ${money(order.isee)}.\n\nChiedo cortesemente di conoscere le eventuali agevolazioni, riduzioni o esenzioni TARI comunali ulteriori rispetto al bonus sociale rifiuti nazionale, con indicazione di requisiti, percentuali applicabili, documentazione necessaria, modalità di presentazione e scadenze.\n\nQualora sia prevista una procedura a domanda, chiedo anche il relativo modulo o il collegamento al servizio online.\n\nResto a disposizione per trasmettere la documentazione attraverso i canali ufficiali dell'Ente.\n\nCordiali saluti,\n${fullName(order)}\n${order.fiscal_code||'[Codice fiscale]'}\n[Codice utenza TARI]\n${order.customer_email||'[Recapito]'}`}
export function createBonusFattoReport(order){const input={isee:Number(order.isee),children:Number(order.children),municipality:{name:order.calculation_municipality}};const result=calculate(input);const doc=new PDFDocument({size:'A4',margins:{top:58,bottom:48,left:48,right:48},bufferPages:true,info:{Title:`BonusFatto - ${order.order_code}`,Author:'BonusFatto.it'}});const chunks=[];doc.on('data',c=>chunks.push(c));const done=new Promise((resolve,reject)=>{doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject)});
doc.moveDown(2);doc.font('Helvetica-Bold').fontSize(29).fillColor(C.blue).text('Bonus',{continued:true}).fillColor(C.green).text('Fatto.it');doc.moveDown(.35);doc.font('Helvetica-Bold').fontSize(20).fillColor(C.dark).text('Relazione personalizzata bonus e agevolazioni 2026');doc.moveDown(.5);body(doc,`Relazione elaborata per ${fullName(order)} sulla base dei dati forniti al momento dell'acquisto.`);kv(doc,[['Codice relazione',order.order_code],['Data elaborazione',dateIt(new Date())],['Cliente',fullName(order)],['Comune analizzato',order.calculation_municipality],['ISEE',money(order.isee)],['Figli a carico',String(order.children??0)]],C.paleBlue,C.blue);box(doc,`ESITO SINTETICO\n${result.benefits.filter(b=>b.amount!=null).length} opportunità con importo stimato + ${result.benefits.filter(b=>b.amount==null).length} voci da verificare senza stima economica.`,C.paleGreen,C.green);h2(doc,'Come leggere il documento');body(doc,'La relazione individua opportunità compatibili con i dati inseriti, ma non certifica automaticamente il diritto alla prestazione. Quando mancano elementi essenziali, la misura viene classificata come da approfondire e viene indicato cosa manca per verificarla.');box(doc,'Il valore economico complessivo è un indicatore teorico delle opportunità rilevate: non è una somma certa, non implica cumulabilità automatica e non costituisce attestazione di spettanza.',C.yellow,C.amber);
doc.addPage();title(doc,'1. Quadro sintetico');kv(doc,[['Stima annua ricorrente',money(result.recurring)],['Massimali / una tantum',money(result.conditional)],['Valore teorico opportunità',money(result.total)]],C.light,C.border);box(doc,'IMPORTANTE\nAnnualità, massimali e una tantum non vanno sommati come se fossero un credito già maturato. La spettanza effettiva dipende dai requisiti specifici di ogni misura.',C.yellow,C.amber);h2(doc,'Legenda attendibilità');badge(doc,'COMPATIBILITÀ ALTA','green');small(doc,'I dati inseriti sono coerenti con i principali requisiti che il simulatore conosce; resta la verifica dell’ente.');doc.moveDown(.6);badge(doc,'DA APPROFONDIRE','yellow');small(doc,'Servono uno o più requisiti che il questionario rapido non raccoglie.');doc.moveDown(.6);badge(doc,'DATI INSUFFICIENTI','red');small(doc,'Il simulatore segnala l’opportunità ma non può attribuire un importo attendibile.');
doc.addPage();title(doc,'2. TARI: bonus nazionale e riduzione comunale');body(doc,'BonusFatto separa i due livelli per evitare sovrapposizioni: il bonus sociale rifiuti nazionale e le eventuali agevolazioni comunali non vanno trattati come una sola percentuale.');if(result.tariNationalEligible){badge(doc,'COMPATIBILITÀ ALTA - BONUS TARI NAZIONALE','green');kv(doc,[['Riduzione indicata dal modello','25% della TARI dovuta'],['Stima in euro',money(result.tariEstimatedSaving)],['Base convenzionale usata',money(result.tariBase)],['Cosa manca per verificarlo','Controllo dell’ISEE/DSU valido e della posizione TARI effettivamente assoggettata al tributo.']],C.paleGreen,C.green)}if(result.tariLocalPercent>0){badge(doc,'COMPATIBILITÀ ALTA - RIDUZIONE COMUNALE','green');kv(doc,[['Comune',order.calculation_municipality],['Riduzione fascia',`${result.tariLocalPercent}%`],['Stima in euro',money(result.tariBase*result.tariLocalPercent/100)],['Modalità',result.tariLocalRule?.applicationRequired?'Agevolazione indicata come soggetta a domanda.':'Verificare la modalità prevista dal Comune.'],['Scadenza',result.tariLocalRule?.deadlineLabel||'Da verificare sulla fonte ufficiale.'],['Cosa manca per verificarla','Conferma della posizione TARI, della procedura attiva e della scadenza presso il Comune.'],['Fonte',result.tariLocalRule?.sourceUrl||'Fonte comunale da verificare']],C.paleBlue,C.blue)}box(doc,'NON SOMMARE AUTOMATICAMENTE LE PERCENTUALI\nL’applicazione concreta e l’eventuale cumulabilità devono essere verificate sulla posizione TARI e sulle regole comunali vigenti.',C.yellow,C.amber);
doc.addPage();title(doc,'3. Agevolazioni individuate');body(doc,'Per ogni misura vengono mostrati la stima del modello, il livello di compatibilità e i dati mancanti per una verifica completa.');for(const b of result.benefits){if(b.id==='tari'||b.id.startsWith('tari-local-'))continue;const[lev,kind]=levelFor(b.id);if(doc.y>690)doc.addPage();badge(doc,lev,kind);h2(doc,b.name);kv(doc,[['Valore nel modello',b.amount==null?'Importo non stimato':`${money(b.amount)}${b.period?` · ${b.period}`:''}`],['Nota',b.description],['Cosa manca per verificarlo',missingFor(b.id)]],kind==='green'?C.paleGreen:kind==='red'?C.paleRed:C.yellow,kind==='green'?C.green:kind==='red'?C.red:C.amber)}
doc.addPage();title(doc,'4. Cosa fare adesso');body(doc,'1. Conserva un ISEE/DSU 2026 valido. È il dato di base per le agevolazioni economiche.');body(doc,`2. Verifica la posizione TARI con il Comune di ${order.calculation_municipality}. Chiedi conferma della fascia comunale, della procedura a domanda e della scadenza effettiva.`);body(doc,'3. Approfondisci le misure familiari. Per le prestazioni che dipendono da età, lavoro, spese o altre condizioni servono dati ulteriori rispetto al calcolo rapido.');body(doc,'4. Considera il valore economico complessivo come orientativo. Non rappresenta un credito già maturato né una somma automaticamente cumulabile.');h2(doc,'Checklist documenti utile');['Attestazione ISEE/DSU 2026','Documento di identità e codice fiscale','Ultimo avviso o bolletta TARI e codice utenza','Dati dei componenti del nucleo familiare','Documentazione relativa a figli e spese specifiche delle misure da approfondire'].forEach(x=>body(doc,`• ${x}`));title(doc,'5. Testo email/PEC pronto per l’Ufficio Tributi');box(doc,customerEmailText(order),C.light,C.border);
doc.addPage();title(doc,'6. Fonti, data di consultazione e avvertenze');if(result.tariLocalRule?.sourceUrl)body(doc,`Fonte TARI comunale utilizzata dal dataset BonusFatto: ${result.tariLocalRule.sourceUrl}`);body(doc,`Data di elaborazione: ${dateIt(new Date())}.`);body(doc,'Metodo: la relazione utilizza le regole e le formule presenti nel motore BonusFatto. Le singole prestazioni vengono classificate in base ai dati effettivamente raccolti e ai requisiti che il simulatore è in grado di valutare.');body(doc,'Aggiornamento: fonti, soglie, importi e scadenze devono riflettere la versione vigente dei dati utilizzati al momento dell’elaborazione.');box(doc,'NOTA LEGALE E INFORMATIVA\nLa relazione ha finalità informativa e orientativa. Non costituisce provvedimento dell’ente, attestazione di spettanza, certificazione fiscale o previdenziale e non sostituisce una verifica presso INPS, ARERA, Agenzia delle Entrate o Comune competente. Requisiti, importi, cumulabilità, disponibilità delle risorse e scadenze possono variare.',C.yellow,C.amber);small(doc,`Relazione generata per ${fullName(order)} · ${order.order_code}`);pageHeaderFooter(doc,order);doc.end();return done}
export{customerEmailText};
